### ISSUE TITLE
Doesn't work on MacOS Montery 12.2.1

### ISSUE THREAD

**Issue by dPowNextdoor** [b1narykid/oneko#11]
## Overview

When running any command (regardless of type given in any ReadMe file, blog, etc.), no executable is made anymore like it was in the older versions of Mac OSX. Nothing is produced except random (non-executable) files in the same tar-extracted directory, not in `/usr/bin/`, `/opt/<dir>/`, etc. so there is no longer any way to execute `oneko` from the terminal.

## Commands attempted

```bash
clang -Wno-parentheses -std=c11 -pedantic -D_DEFAULT_SOURCE oneko.c -o oneko -lc -lm -lX11 -lXext
```

```bash
clang -Wno-parentheses -std=c11 -I/opt/X11/include -L/opt/X11/lib -pedantic -D_DEFAULT_SOURCE oneko.c -o oneko -lc -lm -lX11 -lXext
```

```bash
C_INCLUDE_PATH="/usr/X11R6/include" LIBRARY_PATH="/usr/X11R6/lib" clang -Wno-parentheses -I/opt/X11/include -std=c11 -pedantic -D_DEFAULT_SOURCE oneko.c -o oneko -lc -lm -lX11 -lXext
```

## Details

Specifically with the `-I[...] -L[...]` options, I get the error:

```
oneko.c:745:5: error: implicit declaration of function 'pause' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    pause();
    ^
oneko.c:812:8: warning: extra tokens at end of #endif directive [-Wextra-tokens]
#endif SHAPE
```
